---
- name: Register lsb release
  command: lsb_release -cs
  register: lsb_release

#gpg --keyserver keys.gnupg.net --recv 886DDD89
#gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -

- name: Add torproject apt repository key
  apt_key: id=886DDD89 keyserver=hkp://keys.gnupg.net:80 state=present

- name: Install torproject apt signing gpg key
  apt_key: data="{{ lookup('file', 'torproject.gpg') }}" state=present

- name: Add torproject apt repository
  apt_repository: repo='deb http://deb.torproject.org/torproject.org {{ lsb_release.stdout }} main' state=present update_cache=no

- name: Install tor packages
  apt: name="{{ item }}" state=latest
  with_items:
    - tor
    - tor-arm
    - deb.torproject.org-keyring
    - vidalia 
    - privoxy

- name: Install pentest tools
  apt: name="{{ item }}" state=latest
  with_items:
    - nmap
    - proxychains

- name: Configure tor
  template: > src=torrc.j2 dest=/etc/tor/torrc owner=root group=root mode=0644
  notify: restart tor

- name: Configure privoxy
  template: > src=privoxy.j2 dest=/etc/privoxy/config owner=root group=root mode=0644

- name: Configure proxychains
  template: > src=proxychains.j2 dest=/etc/proxychains.conf owner=root group=root mode=0644

- name: Install tortunnel packages
  apt: name="{{ item }}" state=latest
  with_items:
    - ibboost-system-dev 
    - openssl 
    - automake
    - libssl-dev

- name: Clone git tortunnel
  git: repo=https://github.com/moxie0/tortunnel.git dest=/tmp/tortunnel force=yes

- name: Build tortunnel
  shell: "autoreconf;automake --add-missing;./configure --prefix=/usr/local/;make"
  args:
    chdir: "/tmp/tortunnel"

- name: Get tor exit node ip
  shell: "wget -qO- http://torstatus.blutmagie.de/query_export.php/Tor_query_EXPORT.csv|awk -F"," '{print $3" "$5}'|sort|uniq|sort -n|tail -n 1|awk '{print $2}'"
  register: exit_node_ip